#!/bin/sh

set -e

main()
{
    cd /etc/pam.d

    cp login login.orig

    cat <<EOFlogin > login
# Generated by $0 on $(date)
auth sufficient pam_listfile.so item=tty sense=allow file=/etc/rq-autologin-tty onerr=fail apply=root
@include login.orig
EOFlogin

cat <<EOFttys > /etc/rq-autologin-tty
# Generated by $0 on $(date)
$trusted_console
EOFttys

}

main "$@"
